apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crashloop-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/buleye-ai/ai-lab.git
    targetRevision: main
    path: gitops/demo/crashloop
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
