apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diagnostic-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/buleye-ai/ai-lab.git
    targetRevision: main
    path: gitops/agent/diagnostic-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
